# Generated by Django 4.1.3 on 2022-12-09 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productingredient',
            name='nutrient',
        ),
        migrations.AddField(
            model_name='productingredient',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store_api.ingredient'),
            preserve_default=False,
        ),
    ]
